from __future__ import annotations

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    Float,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
    UniqueConstraint,
)

metadata = MetaData()


def common_columns() -> tuple[Column, ...]:
    return (
        Column("source", String, nullable=False, default="unknown"),
        Column("source_version", String, nullable=False, default="1"),
        Column("created_at", DateTime(timezone=True), nullable=False),
    )


companies = Table(
    "companies",
    metadata,
    Column("company_id", String, primary_key=True),
    Column("ticker", String, nullable=False, unique=True),
    Column("cik", String, nullable=False, unique=True),
    Column("name", String, nullable=False),
    Column("sector", String, nullable=False),
    Column("sector_etf", String, nullable=False),
    Column("fiscal_year_end_month", Integer, nullable=False),
    Column("active", Boolean, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

instruments = Table(
    "instruments",
    metadata,
    Column("instrument_id", String, primary_key=True),
    Column("symbol", String, nullable=False, unique=True),
    Column("name", String, nullable=False),
    Column("asset_class", String, nullable=False),
    Column("currency", String, nullable=False),
    Column("venue", String, nullable=False),
    Column("enabled", Boolean, nullable=False),
    Column("configuration", JSON, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

financials_quarterly = Table(
    "financials_quarterly",
    metadata,
    Column("financial_id", String, primary_key=True),
    Column("company_id", String, nullable=False),
    Column("fiscal_year", Integer, nullable=False),
    Column("fiscal_quarter", String, nullable=False),
    Column("period_start", Date),
    Column("period_end", Date, nullable=False),
    Column("filed_date", Date, nullable=False),
    Column("available_date", Date, nullable=False),
    Column("accession", String, nullable=False),
    Column("form", String, nullable=False),
    Column("selected_tag", String, nullable=False),
    Column("revenue", Float),
    Column("operating_income", Float),
    Column("net_income", Float),
    Column("diluted_eps", Float),
    Column("diluted_shares", Float),
    Column("unit", String, nullable=False),
    Column("amendment", Boolean, nullable=False, default=False),
    Column("quality_status", String, nullable=False),
    *common_columns(),
    UniqueConstraint("company_id", "fiscal_quarter", "accession", name="uq_financial_filing"),
)

company_kpis = Table(
    "company_kpis",
    metadata,
    Column("kpi_id", String, primary_key=True),
    Column("company_id", String, nullable=False),
    Column("fiscal_quarter", String, nullable=False),
    Column("kpi_name", String, nullable=False),
    Column("value", Float, nullable=False),
    Column("unit", String, nullable=False),
    Column("period_end", Date, nullable=False),
    Column("available_date", Date, nullable=False),
    Column("accession", String, nullable=False),
    Column("extraction_method", String, nullable=False),
    Column("evidence_url", Text),
    *common_columns(),
    UniqueConstraint("company_id", "fiscal_quarter", "kpi_name", "accession", name="uq_company_kpi"),
)

earnings_calendar = Table(
    "earnings_calendar",
    metadata,
    Column("event_id", String, primary_key=True),
    Column("company_id", String, nullable=False),
    Column("fiscal_quarter", String, nullable=False),
    Column("earnings_date", Date, nullable=False),
    Column("earnings_time", String),
    Column("timing_confidence", String, nullable=False),
    Column("available_date", Date, nullable=False),
    *common_columns(),
    UniqueConstraint("company_id", "fiscal_quarter", name="uq_earnings_quarter"),
)

market_prices_daily = Table(
    "market_prices_daily",
    metadata,
    Column("price_id", String, primary_key=True),
    Column("symbol", String, nullable=False),
    Column("trading_date", Date, nullable=False),
    Column("raw_close", Float, nullable=False),
    Column("adjusted_close", Float, nullable=False),
    Column("volume", Float),
    Column("currency", String, nullable=False),
    Column("adjustment_status", String, nullable=False),
    *common_columns(),
    UniqueConstraint("symbol", "trading_date", "source", name="uq_market_price"),
)

crypto_features_daily = Table(
    "crypto_features_daily",
    metadata,
    Column("feature_id", String, primary_key=True),
    Column("symbol", String, nullable=False),
    Column("decision_date", Date, nullable=False),
    Column("data_through_date", Date, nullable=False),
    Column("execution_date", Date, nullable=False),
    Column("label_end", Date, nullable=False),
    Column("horizon_days", Integer, nullable=False),
    Column("feature_return_1d", Float, nullable=False),
    Column("feature_return_5d", Float, nullable=False),
    Column("feature_momentum_20d", Float, nullable=False),
    Column("feature_trend_20_100", Float, nullable=False),
    Column("feature_volatility_20d", Float, nullable=False),
    Column("feature_volatility_60d", Float, nullable=False),
    Column("feature_volume_zscore_20d", Float, nullable=False),
    Column("feature_rsi_14d", Float, nullable=False),
    Column("feature_weekday_sin", Float, nullable=False),
    Column("feature_weekday_cos", Float, nullable=False),
    Column("entry_close", Float, nullable=False),
    Column("exit_close", Float, nullable=False),
    Column("target_forward_return", Float, nullable=False),
    Column("target_direction", Integer, nullable=False),
    *common_columns(),
    UniqueConstraint("symbol", "decision_date", "horizon_days", name="uq_crypto_feature"),
)

market_signals_daily = Table(
    "market_signals_daily",
    metadata,
    Column("signal_id", String, primary_key=True),
    Column("instrument_id", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("asset_class", String, nullable=False),
    Column("decision_date", Date, nullable=False),
    Column("data_through_date", Date, nullable=False),
    Column("execution_date", Date, nullable=False),
    Column("label_end_date", Date, nullable=False),
    Column("horizon_days", Integer, nullable=False),
    Column("model_name", String, nullable=False),
    Column("posture", String, nullable=False),
    Column("direction_probability", Float, nullable=False),
    Column("expected_return", Float, nullable=False),
    Column("confidence_score", Float, nullable=False),
    Column("training_samples", Integer, nullable=False),
    Column("calibration_status", String, nullable=False),
    Column("status", String, nullable=False),
    Column("explanation", JSON, nullable=False),
    *common_columns(),
    UniqueConstraint("instrument_id", "decision_date", "horizon_days", "model_name", name="uq_market_signal"),
)

alternative_data_daily = Table(
    "alternative_data_daily",
    metadata,
    Column("observation_id", String, primary_key=True),
    Column("company_id", String, nullable=False),
    Column("signal", String, nullable=False),
    Column("observation_date", Date, nullable=False),
    Column("available_date", Date, nullable=False),
    Column("value", Float, nullable=False),
    Column("unit", String, nullable=False),
    Column("dimensions", JSON),
    *common_columns(),
    UniqueConstraint("company_id", "signal", "observation_date", "source", name="uq_alt_observation"),
)

macro_data = Table(
    "macro_data",
    metadata,
    Column("macro_id", String, primary_key=True),
    Column("series_id", String, nullable=False),
    Column("observation_date", Date, nullable=False),
    Column("available_date", Date, nullable=False),
    Column("vintage_date", Date, nullable=False),
    Column("value", Float, nullable=False),
    Column("unit", String, nullable=False),
    *common_columns(),
    UniqueConstraint("series_id", "observation_date", "vintage_date", "source", name="uq_macro_observation"),
)

features_quarterly = Table(
    "features_quarterly",
    metadata,
    Column("feature_id", String, primary_key=True),
    Column("company_id", String, nullable=False),
    Column("fiscal_quarter", String, nullable=False),
    Column("earnings_date", Date, nullable=False),
    Column("forecast_cutoff_date", Date, nullable=False),
    Column("horizon_days", Integer, nullable=False),
    Column("feature_name", String, nullable=False),
    Column("feature_value", Float),
    Column("feature_family", String, nullable=False),
    Column("maximum_input_available_date", Date, nullable=False),
    Column("transformation_version", String, nullable=False),
    *common_columns(),
    UniqueConstraint(
        "company_id",
        "fiscal_quarter",
        "horizon_days",
        "feature_name",
        "transformation_version",
        name="uq_quarter_feature",
    ),
)

model_runs = Table(
    "model_runs",
    metadata,
    Column("run_id", String, primary_key=True),
    Column("run_timestamp", DateTime(timezone=True), nullable=False),
    Column("git_commit", String, nullable=False),
    Column("random_seed", Integer, nullable=False),
    Column("model_name", String, nullable=False),
    Column("feature_set", JSON, nullable=False),
    Column("training_start", Date),
    Column("training_end", Date),
    Column("test_start", Date),
    Column("test_end", Date),
    Column("hyperparameters", JSON, nullable=False),
    Column("observations", Integer, nullable=False),
    Column("metrics", JSON, nullable=False),
    Column("status", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

forecasts = Table(
    "forecasts",
    metadata,
    Column("forecast_id", String, primary_key=True),
    Column("run_id", String, nullable=False),
    Column("company_id", String, nullable=False),
    Column("fiscal_quarter", String, nullable=False),
    Column("forecast_cutoff_date", Date, nullable=False),
    Column("horizon_days", Integer, nullable=False),
    Column("model_name", String, nullable=False),
    Column("ablation", String, nullable=False),
    Column("target_forecast", Float, nullable=False),
    Column("forecast_revenue", Float, nullable=False),
    Column("actual_revenue", Float),
    Column("interval_low", Float),
    Column("interval_high", Float),
    Column("confidence_score", Float),
    Column("explanation", JSON),
    Column("status", String, nullable=False),
    *common_columns(),
    UniqueConstraint(
        "run_id", "company_id", "fiscal_quarter", "model_name", "horizon_days", "ablation", name="uq_forecast"
    ),
)

consensus_estimates = Table(
    "consensus_estimates",
    metadata,
    Column("estimate_id", String, primary_key=True),
    Column("company_id", String, nullable=False),
    Column("fiscal_quarter", String, nullable=False),
    Column("as_of_date", Date, nullable=False),
    Column("consensus_revenue", Float, nullable=False),
    Column("consensus_eps", Float),
    Column("number_of_analysts", Integer),
    Column("mode", String, nullable=False),
    *common_columns(),
    UniqueConstraint("company_id", "fiscal_quarter", "as_of_date", "mode", name="uq_consensus_estimate"),
)

variant_signals = Table(
    "variant_signals",
    metadata,
    Column("signal_id", String, primary_key=True),
    Column("forecast_id", String, nullable=False),
    Column("estimate_id", String, nullable=False),
    Column("company_id", String, nullable=False),
    Column("fiscal_quarter", String, nullable=False),
    Column("forecast_cutoff_date", Date, nullable=False),
    Column("horizon_days", Integer, nullable=False),
    Column("variant", Float, nullable=False),
    Column("variant_zscore", Float),
    Column("variant_bucket", String, nullable=False),
    Column("confidence_score", Float),
    Column("confidence_components", JSON),
    Column("expectation_mode", String, nullable=False),
    *common_columns(),
    UniqueConstraint("forecast_id", "estimate_id", name="uq_variant_signal"),
)

backtest_results = Table(
    "backtest_results",
    metadata,
    Column("result_id", String, primary_key=True),
    Column("signal_id", String, nullable=False),
    Column("company_id", String, nullable=False),
    Column("event_date", Date, nullable=False),
    Column("window_start", Integer, nullable=False),
    Column("window_end", Integer, nullable=False),
    Column("raw_return", Float, nullable=False),
    Column("benchmark_return", Float),
    Column("sector_return", Float),
    Column("abnormal_return", Float),
    Column("sector_adjusted_return", Float),
    Column("portfolio_weight", Float),
    Column("transaction_cost", Float),
    Column("liquidity_status", String),
    *common_columns(),
    UniqueConstraint("signal_id", "window_start", "window_end", name="uq_backtest_result"),
)

backtest_runs = Table(
    "backtest_runs",
    metadata,
    Column("backtest_run_id", String, primary_key=True),
    Column("strategy_name", String, nullable=False),
    Column("symbol", String),
    Column("asset_class", String, nullable=False),
    Column("protocol", JSON, nullable=False),
    Column("development_metrics", JSON, nullable=False),
    Column("final_test_metrics", JSON, nullable=False),
    Column("full_metrics", JSON, nullable=False),
    Column("robustness", JSON, nullable=False),
    Column("readiness", String, nullable=False),
    Column("readiness_score", Float, nullable=False),
    Column("readiness_reasons", JSON, nullable=False),
    Column("development_start", Date, nullable=False),
    Column("development_end", Date, nullable=False),
    Column("final_test_start", Date, nullable=False),
    Column("final_test_end", Date, nullable=False),
    Column("status", String, nullable=False),
    *common_columns(),
)

backtest_curve = Table(
    "backtest_curve",
    metadata,
    Column("curve_id", String, primary_key=True),
    Column("backtest_run_id", String, nullable=False),
    Column("curve_date", Date, nullable=False),
    Column("phase", String, nullable=False),
    Column("gross_return", Float, nullable=False),
    Column("net_return", Float, nullable=False),
    Column("gross_equity", Float, nullable=False),
    Column("net_equity", Float, nullable=False),
    Column("drawdown", Float, nullable=False),
    Column("gross_exposure", Float, nullable=False),
    Column("turnover", Float, nullable=False),
    Column("costs", Float, nullable=False),
    *common_columns(),
    UniqueConstraint("backtest_run_id", "curve_date", name="uq_backtest_curve"),
)

backtest_positions = Table(
    "backtest_positions",
    metadata,
    Column("position_id", String, primary_key=True),
    Column("backtest_run_id", String, nullable=False),
    Column("signal_id", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("phase", String, nullable=False),
    Column("decision_date", Date, nullable=False),
    Column("execution_date", Date, nullable=False),
    Column("label_end_date", Date, nullable=False),
    Column("posture", String, nullable=False),
    Column("weight", Float, nullable=False),
    Column("gross_exposure", Float, nullable=False),
    Column("turnover", Float, nullable=False),
    Column("realized_return", Float, nullable=False),
    Column("gross_return", Float, nullable=False),
    Column("net_return", Float, nullable=False),
    Column("cost", Float, nullable=False),
    *common_columns(),
    UniqueConstraint("backtest_run_id", "signal_id", name="uq_backtest_position"),
)

backtest_sensitivity = Table(
    "backtest_sensitivity",
    metadata,
    Column("sensitivity_id", String, primary_key=True),
    Column("backtest_run_id", String, nullable=False),
    Column("scenario", String, nullable=False),
    Column("parameters", JSON, nullable=False),
    Column("metrics", JSON, nullable=False),
    *common_columns(),
    UniqueConstraint("backtest_run_id", "scenario", name="uq_backtest_sensitivity"),
)

data_quality_issues = Table(
    "data_quality_issues",
    metadata,
    Column("issue_id", String, primary_key=True),
    Column("stage", String, nullable=False),
    Column("entity_key", String, nullable=False),
    Column("severity", String, nullable=False),
    Column("rule", String, nullable=False),
    Column("observed_value", Text),
    Column("message", Text, nullable=False),
    Column("detected_at", DateTime(timezone=True), nullable=False),
    *common_columns(),
)

pipeline_runs = Table(
    "pipeline_runs",
    metadata,
    Column("pipeline_run_id", String, primary_key=True),
    Column("command", String, nullable=False),
    Column("mode", String, nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("ended_at", DateTime(timezone=True)),
    Column("config_hash", String, nullable=False),
    Column("git_commit", String, nullable=False),
    Column("row_counts", JSON),
    Column("status", String, nullable=False),
    Column("error_summary", Text),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

# Version 2 adds append-only intraday research records.  These tables are
# deliberately parallel to the daily earnings schema so legacy natural keys
# and historical queries retain their existing meaning.
schema_versions = Table(
    "schema_versions",
    metadata,
    Column("version", Integer, primary_key=True, autoincrement=False),
    Column("applied_at", DateTime(timezone=True), nullable=False),
)

market_bars = Table(
    "market_bars",
    metadata,
    Column("bar_id", String, primary_key=True),
    Column("provider", String, nullable=False),
    Column("feed", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("open_timestamp", DateTime(timezone=True), nullable=False),
    Column("close_timestamp", DateTime(timezone=True), nullable=False),
    Column("available_at", DateTime(timezone=True), nullable=False),
    Column("source_available_at", DateTime(timezone=True)),
    Column("observed_at", DateTime(timezone=True)),
    Column("vintage_fidelity", String),
    Column("revision", Integer, nullable=False),
    Column("finalized", Boolean, nullable=False),
    Column("open", Float, nullable=False),
    Column("high", Float, nullable=False),
    Column("low", Float, nullable=False),
    Column("close", Float, nullable=False),
    Column("volume", Float, nullable=False),
    Column("vwap", Float),
    Column("trade_count", Integer),
    Column("quote_volume", Float),
    Column("taker_buy_base_volume", Float),
    Column("taker_buy_quote_volume", Float),
    Column("payload_hash", String, nullable=False),
    *common_columns(),
    UniqueConstraint(
        "provider",
        "feed",
        "symbol",
        "interval",
        "open_timestamp",
        "revision",
        "available_at",
        name="uq_market_bar_revision",
    ),
)

dataset_coverage_requests = Table(
    "dataset_coverage_requests",
    metadata,
    Column("coverage_request_id", String, primary_key=True),
    Column("provider", String, nullable=False),
    Column("feed", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("requested_start", DateTime(timezone=True), nullable=False),
    Column("requested_end", DateTime(timezone=True), nullable=False),
    Column("requested_at", DateTime(timezone=True), nullable=False),
    Column("force", Boolean, nullable=False),
    Column("status", String, nullable=False),
    Column("dataset_hash", String, nullable=False),
    Column("row_count", Integer, nullable=False),
    Column("gaps", JSON, nullable=False),
    *common_columns(),
    UniqueConstraint(
        "provider",
        "feed",
        "symbol",
        "interval",
        "requested_start",
        "requested_end",
        "requested_at",
        name="uq_dataset_coverage_request_timestamp",
    ),
)

strategy_runs = Table(
    "strategy_runs",
    metadata,
    Column("strategy_run_id", String, primary_key=True),
    Column("dataset_hash", String, nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("family", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("mode", String, nullable=False),
    Column("run_timestamp", DateTime(timezone=True), nullable=False),
    Column("parameters", JSON, nullable=False),
    Column("status", String, nullable=False),
    Column("metrics", JSON),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("ended_at", DateTime(timezone=True)),
    *common_columns(),
    UniqueConstraint(
        "dataset_hash",
        "strategy_id",
        "strategy_version",
        "symbol",
        "interval",
        "mode",
        "run_timestamp",
        name="uq_strategy_run_timestamp",
    ),
)

strategy_signals = Table(
    "strategy_signals",
    metadata,
    Column("strategy_signal_id", String, primary_key=True),
    Column("strategy_run_id", String, nullable=False),
    Column("dataset_hash", String, nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("mode", String, nullable=False),
    Column("decision_timestamp", DateTime(timezone=True), nullable=False),
    Column("data_through_timestamp", DateTime(timezone=True), nullable=False),
    Column("executable_at", DateTime(timezone=True), nullable=False),
    Column("signal", Integer, nullable=False),
    Column("strength", Float, nullable=False),
    Column("reason", Text, nullable=False),
    *common_columns(),
    UniqueConstraint(
        "dataset_hash",
        "strategy_id",
        "strategy_version",
        "symbol",
        "interval",
        "mode",
        "decision_timestamp",
        name="uq_strategy_signal_timestamp",
    ),
)

ensemble_weights = Table(
    "ensemble_weights",
    metadata,
    Column("weight_id", String, primary_key=True),
    Column("strategy_run_id", String, nullable=False),
    Column("dataset_hash", String, nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("family", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("mode", String, nullable=False),
    Column("effective_at", DateTime(timezone=True), nullable=False),
    Column("weight", Float, nullable=False),
    Column("evidence", JSON, nullable=False),
    *common_columns(),
    CheckConstraint("weight >= 0", name="ck_ensemble_weight_nonnegative"),
    UniqueConstraint(
        "dataset_hash",
        "strategy_id",
        "strategy_version",
        "symbol",
        "interval",
        "mode",
        "effective_at",
        name="uq_ensemble_weight_timestamp",
    ),
)

strategy_executions = Table(
    "strategy_executions",
    metadata,
    Column("execution_id", String, primary_key=True),
    Column("strategy_run_id", String, nullable=False),
    Column("dataset_hash", String, nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("mode", String, nullable=False),
    Column("decision_timestamp", DateTime(timezone=True), nullable=False),
    Column("execution_timestamp", DateTime(timezone=True), nullable=False),
    Column("side", String, nullable=False),
    Column("quantity", Float, nullable=False),
    Column("fill_price", Float),
    Column("fees", Float, nullable=False),
    Column("status", String, nullable=False),
    Column("reason", Text),
    *common_columns(),
    UniqueConstraint(
        "dataset_hash",
        "strategy_id",
        "strategy_version",
        "symbol",
        "interval",
        "mode",
        "decision_timestamp",
        "execution_timestamp",
        name="uq_strategy_execution_timestamp",
    ),
)

strategy_run_signal_links = Table(
    "strategy_run_signal_links",
    metadata,
    Column("run_signal_link_id", String, primary_key=True),
    Column("strategy_run_id", String, nullable=False),
    Column("strategy_signal_id", String, nullable=False),
    *common_columns(),
    UniqueConstraint(
        "strategy_run_id",
        "strategy_signal_id",
        name="uq_strategy_run_signal_link",
    ),
)

strategy_run_execution_links = Table(
    "strategy_run_execution_links",
    metadata,
    Column("run_execution_link_id", String, primary_key=True),
    Column("strategy_run_id", String, nullable=False),
    Column("execution_id", String, nullable=False),
    *common_columns(),
    UniqueConstraint(
        "strategy_run_id",
        "execution_id",
        name="uq_strategy_run_execution_link",
    ),
)

learning_trials = Table(
    "learning_trials",
    metadata,
    Column("trial_id", String, primary_key=True),
    Column("learning_run_id", String, nullable=False),
    Column("candidate_hash", String, nullable=False),
    Column("dataset_hash", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("mode", String, nullable=False),
    Column("evaluated_at", DateTime(timezone=True), nullable=False),
    Column("candidate", JSON, nullable=False),
    Column("fitness", Float),
    Column("status", String, nullable=False),
    Column("error_summary", Text),
    *common_columns(),
    UniqueConstraint("learning_run_id", "candidate_hash", "evaluated_at", name="uq_learning_trial_timestamp"),
)

discovered_rules = Table(
    "discovered_rules",
    metadata,
    Column("rule_id", String, primary_key=True),
    Column("learning_run_id", String, nullable=False),
    Column("rule_hash", String, nullable=False),
    Column("rule_version", String, nullable=False),
    Column("dataset_hash", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("discovered_at", DateTime(timezone=True), nullable=False),
    Column("state", String, nullable=False),
    Column("rule", JSON, nullable=False),
    Column("evidence", JSON, nullable=False),
    *common_columns(),
    UniqueConstraint(
        "rule_hash",
        "rule_version",
        "dataset_hash",
        "symbol",
        "interval",
        "discovered_at",
        name="uq_discovered_rule_timestamp",
    ),
)

causal_audits = Table(
    "causal_audits",
    metadata,
    Column("audit_id", String, primary_key=True),
    Column("dataset_hash", String, nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("mode", String, nullable=False),
    Column("audited_at", DateTime(timezone=True), nullable=False),
    Column("passed", Boolean, nullable=False),
    Column("details", JSON, nullable=False),
    *common_columns(),
    UniqueConstraint(
        "dataset_hash",
        "strategy_id",
        "strategy_version",
        "symbol",
        "interval",
        "mode",
        "audited_at",
        name="uq_causal_audit_timestamp",
    ),
)

# Version 5 records trial-aware, resumable Deep Research evidence. Workers never
# write these tables directly; the coordinator is the single ordered writer.
deep_research_runs = Table(
    "deep_research_runs",
    metadata,
    Column("run_id", String, primary_key=True),
    Column("protocol_id", String, nullable=False),
    Column("dataset_hash", String, nullable=False),
    Column("code_hash", String, nullable=False),
    Column("search_space_hash", String, nullable=False),
    Column("cost_policy_hash", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("provider", String, nullable=False),
    Column("feed", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("seed", Integer, nullable=False),
    Column("workers", Integer, nullable=False),
    Column("trial_budget", Integer),
    Column("continuous", Boolean, nullable=False),
    Column("cycle_budget", Integer, nullable=False),
    Column("final_test_start", DateTime(timezone=True), nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("ended_at", DateTime(timezone=True)),
    Column("state", String, nullable=False),
    Column("terminal_reason", Text),
    Column("protocol", JSON, nullable=False),
    *common_columns(),
)

deep_research_trials = Table(
    "deep_research_trials",
    metadata,
    Column("trial_id", String, primary_key=True),
    Column("run_id", String, nullable=False),
    Column("ordinal", Integer, nullable=False),
    Column("persisted_sequence", Integer, nullable=False),
    Column("generation", Integer, nullable=False),
    Column("candidate_hash", String, nullable=False),
    Column("definition", JSON, nullable=False),
    Column("status", String, nullable=False),
    Column("attempted_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True)),
    Column("fitness", Float),
    Column("error_summary", Text),
    *common_columns(),
    UniqueConstraint("run_id", "ordinal", name="uq_deep_research_trial_ordinal"),
)

deep_research_fold_metrics = Table(
    "deep_research_fold_metrics",
    metadata,
    Column("fold_metric_id", String, primary_key=True),
    Column("run_id", String, nullable=False),
    Column("ordinal", Integer, nullable=False),
    Column("fold_index", Integer, nullable=False),
    Column("metrics", JSON, nullable=False),
    *common_columns(),
    UniqueConstraint("run_id", "ordinal", "fold_index", name="uq_deep_research_fold_metric"),
)

deep_research_stress_metrics = Table(
    "deep_research_stress_metrics",
    metadata,
    Column("stress_metric_id", String, primary_key=True),
    Column("run_id", String, nullable=False),
    Column("ordinal", Integer, nullable=False),
    Column("scenario", String, nullable=False),
    Column("metrics", JSON, nullable=False),
    Column("passed", Boolean, nullable=False),
    *common_columns(),
    UniqueConstraint("run_id", "ordinal", "scenario", name="uq_deep_research_stress_metric"),
)

deep_research_promotions = Table(
    "deep_research_promotions",
    metadata,
    Column("promotion_id", String, primary_key=True),
    Column("run_id", String, nullable=False),
    Column("candidate_hash", String),
    Column("incumbent_hash", String),
    Column("evaluated_at", DateTime(timezone=True), nullable=False),
    Column("promoted", Boolean, nullable=False),
    Column("outcome", String, nullable=False),
    Column("score", Float),
    Column("evidence", JSON, nullable=False),
    Column("failed_gates", JSON, nullable=False),
    *common_columns(),
)

deep_research_checkpoints = Table(
    "deep_research_checkpoints",
    metadata,
    Column("checkpoint_id", String, primary_key=True),
    Column("run_id", String, nullable=False),
    Column("protocol_id", String, nullable=False),
    Column("next_ordinal", Integer, nullable=False),
    Column("generation", Integer, nullable=False),
    Column("payload", JSON, nullable=False),
    Column("checkpointed_at", DateTime(timezone=True), nullable=False),
    *common_columns(),
    UniqueConstraint("run_id", "next_ordinal", "generation", name="uq_deep_research_checkpoint"),
)

deep_research_resource_samples = Table(
    "deep_research_resource_samples",
    metadata,
    Column("resource_sample_id", String, primary_key=True),
    Column("run_id", String, nullable=False),
    Column("sampled_at", DateTime(timezone=True), nullable=False),
    Column("active_workers", Integer, nullable=False),
    Column("queued_trials", Integer, nullable=False),
    Column("memory_bytes", Integer),
    Column("thermal_state", String, nullable=False),
    *common_columns(),
)

# Version 4 adds broker execution and live-readiness evidence. These records
# remain parallel to the v3 intraday research tables: research evidence can
# propose an intent, but only this ledger records external broker effects.
broker_sessions = Table(
    "broker_sessions",
    metadata,
    Column("session_id", String, primary_key=True),
    Column("environment", String, nullable=False),
    Column("account_suffix", String, nullable=False),
    Column("code_hash", String, nullable=False),
    Column("config_hash", String, nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("ended_at", DateTime(timezone=True)),
    Column("last_heartbeat_at", DateTime(timezone=True), nullable=False),
    Column("status", String, nullable=False),
    Column("terminal_reason", Text),
    *common_columns(),
)

broker_order_intents = Table(
    "broker_order_intents",
    metadata,
    Column("intent_id", String, primary_key=True),
    Column("session_id", String, nullable=False),
    Column("environment", String, nullable=False),
    Column("account_suffix", String, nullable=False),
    Column("cohort_hash", String, nullable=False),
    Column("decision_hash", String, nullable=False),
    Column("provider", String, nullable=False),
    Column("feed", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("decision_timestamp", DateTime(timezone=True), nullable=False),
    Column("client_order_id", String, nullable=False),
    Column("request", JSON, nullable=False),
    Column("status", String, nullable=False),
    *common_columns(),
    UniqueConstraint("environment", "account_suffix", "client_order_id", name="uq_broker_intent_client_id"),
)

broker_orders = Table(
    "broker_orders",
    metadata,
    Column("order_record_id", String, primary_key=True),
    Column("session_id", String, nullable=False),
    Column("intent_id", String, nullable=False),
    Column("environment", String, nullable=False),
    Column("account_suffix", String, nullable=False),
    Column("broker_order_id", String, nullable=False),
    Column("client_order_id", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("side", String, nullable=False),
    Column("quantity", Numeric(38, 12), nullable=False),
    Column("filled_quantity", Numeric(38, 12), nullable=False),
    Column("limit_price", Numeric(38, 12), nullable=False),
    Column("filled_average_price", Numeric(38, 12)),
    Column("status", String, nullable=False),
    Column("submitted_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("received_at", DateTime(timezone=True), nullable=False),
    Column("request", JSON, nullable=False),
    *common_columns(),
    CheckConstraint("quantity > 0", name="ck_broker_order_quantity_positive"),
    CheckConstraint("filled_quantity >= 0", name="ck_broker_order_filled_nonnegative"),
    CheckConstraint("limit_price > 0", name="ck_broker_order_limit_positive"),
    UniqueConstraint("environment", "account_suffix", "broker_order_id", name="uq_broker_order_identity"),
    UniqueConstraint("environment", "account_suffix", "client_order_id", name="uq_broker_order_client_id"),
)

broker_order_events = Table(
    "broker_order_events",
    metadata,
    Column("order_event_id", String, primary_key=True),
    Column("event_identity", String, nullable=False, unique=True),
    Column("event_hash", String, nullable=False),
    Column("session_id", String, nullable=False),
    Column("environment", String, nullable=False),
    Column("account_suffix", String, nullable=False),
    Column("broker_order_id", String, nullable=False),
    Column("client_order_id", String, nullable=False),
    Column("event", String, nullable=False),
    Column("known_event", Boolean, nullable=False),
    Column("status", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("side", String, nullable=False),
    Column("quantity", Numeric(38, 12), nullable=False),
    Column("fill_price", Numeric(38, 12)),
    Column("cumulative_filled_quantity", Numeric(38, 12), nullable=False),
    Column("broker_timestamp", DateTime(timezone=True), nullable=False),
    Column("received_at", DateTime(timezone=True), nullable=False),
    Column("raw_payload_hash", String, nullable=False),
    Column("payload", JSON, nullable=False),
    *common_columns(),
    CheckConstraint("quantity >= 0", name="ck_broker_event_quantity_nonnegative"),
    CheckConstraint("cumulative_filled_quantity >= 0", name="ck_broker_event_filled_nonnegative"),
)

broker_account_snapshots = Table(
    "broker_account_snapshots",
    metadata,
    Column("account_snapshot_id", String, primary_key=True),
    Column("session_id", String, nullable=False),
    Column("environment", String, nullable=False),
    Column("account_suffix", String, nullable=False),
    Column("status", String, nullable=False),
    Column("equity", Numeric(38, 12), nullable=False),
    Column("buying_power", Numeric(38, 12), nullable=False),
    Column("trading_blocked", Boolean, nullable=False),
    Column("pattern_day_trader", Boolean, nullable=False),
    Column("shorting_enabled", Boolean, nullable=False),
    Column("received_at", DateTime(timezone=True), nullable=False),
    *common_columns(),
    CheckConstraint("equity >= 0", name="ck_broker_account_equity_nonnegative"),
    CheckConstraint("buying_power >= 0", name="ck_broker_account_buying_power_nonnegative"),
    UniqueConstraint("session_id", "received_at", name="uq_broker_account_snapshot_receipt"),
)

broker_positions = Table(
    "broker_positions",
    metadata,
    Column("position_snapshot_id", String, primary_key=True),
    Column("reconciliation_id", String, nullable=False),
    Column("session_id", String, nullable=False),
    Column("environment", String, nullable=False),
    Column("account_suffix", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("broker_quantity", Numeric(38, 12), nullable=False),
    Column("local_quantity", Numeric(38, 12), nullable=False),
    Column("broker_market_value", Numeric(38, 12), nullable=False),
    Column("local_market_value", Numeric(38, 12), nullable=False),
    Column("average_entry_price", Numeric(38, 12), nullable=False),
    Column("current_price", Numeric(38, 12), nullable=False),
    Column("unrealized_pnl", Numeric(38, 12), nullable=False),
    Column("mismatch_state", String, nullable=False),
    Column("received_at", DateTime(timezone=True), nullable=False),
    *common_columns(),
    UniqueConstraint("reconciliation_id", "symbol", name="uq_broker_position_reconciliation_symbol"),
)

risk_decisions = Table(
    "risk_decisions",
    metadata,
    Column("risk_decision_id", String, primary_key=True),
    Column("session_id", String, nullable=False),
    Column("intent_id", String, nullable=False),
    Column("environment", String, nullable=False),
    Column("account_suffix", String, nullable=False),
    Column("input_hash", String, nullable=False),
    Column("policy_hash", String, nullable=False),
    Column("allowed", Boolean, nullable=False),
    Column("reasons", JSON, nullable=False),
    Column("limits", JSON, nullable=False),
    Column("utilization", JSON, nullable=False),
    Column("decided_at", DateTime(timezone=True), nullable=False),
    *common_columns(),
    UniqueConstraint("intent_id", "input_hash", "policy_hash", name="uq_risk_decision_evidence"),
)

reconciliation_runs = Table(
    "reconciliation_runs",
    metadata,
    Column("reconciliation_id", String, primary_key=True),
    Column("session_id", String, nullable=False),
    Column("environment", String, nullable=False),
    Column("account_suffix", String, nullable=False),
    Column("compared_at", DateTime(timezone=True), nullable=False),
    Column("open_order_mismatches", Integer, nullable=False),
    Column("position_mismatches", Integer, nullable=False),
    Column("account_mismatches", Integer, nullable=False),
    Column("unresolved_mismatch_count", Integer, nullable=False),
    Column("status", String, nullable=False),
    Column("details", JSON, nullable=False),
    *common_columns(),
    CheckConstraint("open_order_mismatches >= 0", name="ck_reconciliation_order_mismatches"),
    CheckConstraint("position_mismatches >= 0", name="ck_reconciliation_position_mismatches"),
    CheckConstraint("account_mismatches >= 0", name="ck_reconciliation_account_mismatches"),
)

trading_health_events = Table(
    "trading_health_events",
    metadata,
    Column("health_event_id", String, primary_key=True),
    Column("session_id", String, nullable=False),
    Column("environment", String, nullable=False),
    Column("account_suffix", String, nullable=False),
    Column("event", String, nullable=False),
    Column("severity", String, nullable=False),
    Column("details", JSON, nullable=False),
    Column("observed_at", DateTime(timezone=True), nullable=False),
    *common_columns(),
)

forward_evidence_daily = Table(
    "forward_evidence_daily",
    metadata,
    Column("forward_evidence_id", String, primary_key=True),
    Column("cohort_hash", String, nullable=False),
    Column("period_start", DateTime(timezone=True), nullable=False),
    Column("period_end", DateTime(timezone=True), nullable=False),
    Column("closed_trades", Integer, nullable=False),
    Column("paper_net_return", Numeric(38, 12)),
    Column("stressed_net_return", Numeric(38, 12)),
    Column("drawdown", Numeric(38, 12)),
    Column("reconciliation_mismatches", Integer, nullable=False),
    Column("health_breakers", Integer, nullable=False),
    Column("status", String, nullable=False),
    Column("evidence", JSON, nullable=False),
    Column("closed_at", DateTime(timezone=True), nullable=False),
    *common_columns(),
    UniqueConstraint("cohort_hash", "period_start", "period_end", name="uq_forward_evidence_period"),
)

readiness_receipts = Table(
    "readiness_receipts",
    metadata,
    Column("readiness_receipt_id", String, primary_key=True),
    Column("cohort_hash", String, nullable=False),
    Column("evidence_hash", String, nullable=False),
    Column("policy_hash", String, nullable=False),
    Column("gates", JSON, nullable=False),
    Column("issued_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("status", String, nullable=False),
    Column("invalidated_at", DateTime(timezone=True)),
    Column("invalidation_reason", Text),
    *common_columns(),
    UniqueConstraint("cohort_hash", "evidence_hash", "policy_hash", "issued_at", name="uq_readiness_receipt"),
)

trading_arms = Table(
    "trading_arms",
    metadata,
    Column("arm_id", String, primary_key=True),
    Column("environment", String, nullable=False),
    Column("account_suffix", String, nullable=False),
    Column("readiness_receipt_id", String, nullable=False),
    Column("readiness_receipt_hash", String, nullable=False),
    Column("limits", JSON, nullable=False),
    Column("effective_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("status", String, nullable=False),
    Column("ended_at", DateTime(timezone=True)),
    Column("terminal_reason", Text),
    *common_columns(),
)

monitor_sessions = Table(
    "monitor_sessions",
    metadata,
    Column("session_id", String, primary_key=True),
    Column("config_hash", String, nullable=False),
    Column("cohort_hash", String, nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("ended_at", DateTime(timezone=True)),
    Column("status", String, nullable=False),
    Column("terminal_reason", Text),
    *common_columns(),
)

monitor_setups = Table(
    "monitor_setups",
    metadata,
    Column("setup_id", String, primary_key=True),
    Column("session_id", String, nullable=False),
    Column("provider", String, nullable=False),
    Column("feed", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("plan", JSON, nullable=False),
    Column("current_state", String, nullable=False),
    *common_columns(),
)

monitor_transitions = Table(
    "monitor_transitions",
    metadata,
    Column("transition_id", String, primary_key=True),
    Column("event_id", String, nullable=False, unique=True),
    Column("setup_id", String, nullable=False),
    Column("from_state", String, nullable=False),
    Column("to_state", String, nullable=False),
    Column("occurred_at", DateTime(timezone=True), nullable=False),
    Column("reason", Text, nullable=False),
    Column("actual_fill", Numeric(38, 12)),
    Column("payload_hash", String, nullable=False),
    Column("payload", JSON, nullable=False),
    *common_columns(),
)

monitor_notification_receipts = Table(
    "monitor_notification_receipts",
    metadata,
    Column("receipt_id", String, primary_key=True),
    Column("event_id", String, nullable=False, unique=True),
    Column("delivered_at", DateTime(timezone=True), nullable=False),
    Column("status", String, nullable=False),
    *common_columns(),
)

monitor_health_events = Table(
    "monitor_health_events",
    metadata,
    Column("health_event_id", String, primary_key=True),
    Column("session_id", String, nullable=False),
    Column("provider", String),
    Column("feed", String),
    Column("status", String, nullable=False),
    Column("reason", Text),
    Column("occurred_at", DateTime(timezone=True), nullable=False),
    Column("details", JSON, nullable=False),
    *common_columns(),
)

monitor_decisions = Table(
    "monitor_decisions",
    metadata,
    Column("decision_id", String, primary_key=True),
    Column("session_id", String, nullable=False),
    Column("provider", String, nullable=False),
    Column("feed", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("decision_time", DateTime(timezone=True), nullable=False),
    Column("status", String, nullable=False),
    Column("reasons", JSON, nullable=False),
    Column("evidence", JSON, nullable=False),
    *common_columns(),
)

monitor_finalized_bars = Table(
    "monitor_finalized_bars",
    metadata,
    Column("bar_id", String, primary_key=True),
    Column("session_id", String, nullable=False),
    Column("provider", String, nullable=False),
    Column("feed", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("interval", String, nullable=False),
    Column("start_at", DateTime(timezone=True), nullable=False),
    Column("end_at", DateTime(timezone=True), nullable=False),
    Column("revision", Integer, nullable=False),
    Column("payload", JSON, nullable=False),
    *common_columns(),
)

live_market_events = Table(
    "live_market_events",
    metadata,
    Column("event_id", String, primary_key=True),
    Column("session_id", String, nullable=False),
    Column("source_event_id", String, nullable=False),
    Column("provider", String, nullable=False),
    Column("feed", String, nullable=False),
    Column("symbol", String, nullable=False),
    Column("event_type", String, nullable=False),
    Column("provider_time", DateTime(timezone=True), nullable=False),
    Column("received_at", DateTime(timezone=True), nullable=False),
    Column("processed_at", DateTime(timezone=True), nullable=False),
    Column("sequence", Integer),
    Column("payload_hash", String, nullable=False),
    Column("payload", JSON, nullable=False),
    *common_columns(),
    UniqueConstraint("session_id", "source_event_id", name="uq_live_market_event_source"),
)

TABLES = {table.name: table for table in metadata.tables.values()}

NATURAL_KEYS: dict[str, tuple[str, ...]] = {
    "companies": ("company_id",),
    "instruments": ("instrument_id",),
    "financials_quarterly": ("company_id", "fiscal_quarter", "accession"),
    "company_kpis": ("company_id", "fiscal_quarter", "kpi_name", "accession"),
    "earnings_calendar": ("company_id", "fiscal_quarter"),
    "market_prices_daily": ("symbol", "trading_date", "source"),
    "crypto_features_daily": ("symbol", "decision_date", "horizon_days"),
    "market_signals_daily": ("instrument_id", "decision_date", "horizon_days", "model_name"),
    "alternative_data_daily": ("company_id", "signal", "observation_date", "source"),
    "macro_data": ("series_id", "observation_date", "vintage_date", "source"),
    "features_quarterly": ("company_id", "fiscal_quarter", "horizon_days", "feature_name", "transformation_version"),
    "forecasts": ("run_id", "company_id", "fiscal_quarter", "model_name", "horizon_days", "ablation"),
    "consensus_estimates": ("company_id", "fiscal_quarter", "as_of_date", "mode"),
    "variant_signals": ("forecast_id", "estimate_id"),
    "backtest_results": ("signal_id", "window_start", "window_end"),
    "backtest_runs": ("backtest_run_id",),
    "backtest_curve": ("backtest_run_id", "curve_date"),
    "backtest_positions": ("backtest_run_id", "signal_id"),
    "backtest_sensitivity": ("backtest_run_id", "scenario"),
    "market_bars": ("provider", "feed", "symbol", "interval", "open_timestamp", "revision", "available_at"),
    "dataset_coverage_requests": (
        "provider",
        "feed",
        "symbol",
        "interval",
        "requested_start",
        "requested_end",
        "requested_at",
    ),
    "strategy_runs": ("dataset_hash", "strategy_id", "strategy_version", "symbol", "interval", "mode", "run_timestamp"),
    "strategy_signals": (
        "dataset_hash",
        "strategy_id",
        "strategy_version",
        "symbol",
        "interval",
        "mode",
        "decision_timestamp",
    ),
    "ensemble_weights": (
        "dataset_hash",
        "strategy_id",
        "strategy_version",
        "symbol",
        "interval",
        "mode",
        "effective_at",
    ),
    "strategy_executions": (
        "dataset_hash",
        "strategy_id",
        "strategy_version",
        "symbol",
        "interval",
        "mode",
        "decision_timestamp",
        "execution_timestamp",
    ),
    "strategy_run_signal_links": ("strategy_run_id", "strategy_signal_id"),
    "strategy_run_execution_links": ("strategy_run_id", "execution_id"),
    "learning_trials": ("learning_run_id", "candidate_hash", "evaluated_at"),
    "discovered_rules": ("rule_hash", "rule_version", "dataset_hash", "symbol", "interval", "discovered_at"),
    "causal_audits": (
        "dataset_hash",
        "strategy_id",
        "strategy_version",
        "symbol",
        "interval",
        "mode",
        "audited_at",
    ),
    "deep_research_runs": ("run_id",),
    "deep_research_trials": ("run_id", "ordinal"),
    "deep_research_fold_metrics": ("run_id", "ordinal", "fold_index"),
    "deep_research_stress_metrics": ("run_id", "ordinal", "scenario"),
    "deep_research_promotions": ("promotion_id",),
    "deep_research_checkpoints": ("run_id", "next_ordinal", "generation"),
    "deep_research_resource_samples": ("resource_sample_id",),
    "broker_sessions": ("session_id",),
    "broker_order_intents": ("intent_id",),
    "broker_orders": ("environment", "account_suffix", "broker_order_id"),
    "broker_order_events": ("event_identity",),
    "broker_account_snapshots": ("session_id", "received_at"),
    "broker_positions": ("reconciliation_id", "symbol"),
    "risk_decisions": ("intent_id", "input_hash", "policy_hash"),
    "reconciliation_runs": ("reconciliation_id",),
    "trading_health_events": ("health_event_id",),
    "forward_evidence_daily": ("cohort_hash", "period_start", "period_end"),
    "readiness_receipts": ("cohort_hash", "evidence_hash", "policy_hash", "issued_at"),
    "trading_arms": ("arm_id",),
    "monitor_sessions": ("session_id",),
    "monitor_setups": ("setup_id",),
    "monitor_transitions": ("event_id",),
    "monitor_notification_receipts": ("event_id",),
    "monitor_health_events": ("health_event_id",),
    "monitor_decisions": ("decision_id",),
    "monitor_finalized_bars": ("bar_id",),
    "live_market_events": ("session_id", "source_event_id"),
}
